### ISSUE TITLE
[FEAT]: Is there a way to browse the icons (name + appearance)?

### ISSUE THREAD

**Issue by divStar** [shinokada/svelte-google-materialdesign-icons#1]
### Description

Hi there!

Great library! I am liking it so far 😄 .

Do you happen to know if there is a way to not just see a list of icon names, but also their appearance? e.g. similar to https://materialdesignicons.com/ ?

I just don't know which icons are which.

**Comment by shinokada** [comment]
You can find the icon names [here](https://github.com/shinokada/svelte-google-materialdesign-icons/blob/main/icon-list.md).

The original SVG icon sets are from [here](https://github.com/marella/material-design-icons/tree/main/svg/filled)
Since a component name can't start with a number, if a file starts with a number, `A` is prefixed.
For example, 30fps_select will be `A30fps_select.svelte`.

You can find icon images at https://fonts.google.com/icons?selected=Material+Icons

**Comment by divStar** [comment]
Thank you! The last URL was what I was looking.
